### ISSUE TITLE
Memory leaks reading from buffer

### ISSUE THREAD

**Issue by randy408** [nih-at/libzip#110]
I'm in the process of creating a fuzz target for libzip and it gets caught up with memory leaks, I'm not sure if I'm using the API correctly.

```
Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x4c6293 in malloc (/libzip/regress/a.out+0x4c6293)
    #1 0x500e58 in _zip_source_new (/libzip/regress/a.out+0x500e58)
    #2 0x500db9 in zip_source_function_create (/libzip/regress/a.out+0x500db9)
    #3 0x4fe8a2 in zip_source_buffer_fragment_create (/libzip/regress/a.out+0x4fe8a2)
    #4 0x4fe75c in zip_source_buffer_create (/libzip/regress/a.out+0x4fe75c)
    #5 0x4f5563 in LLVMFuzzerTestOneInput /libzip/regress/zip_read_fuzzer_.c:16:16
    #6 0x4f58d3 in main /libzip/regress/zip_read_fuzzer_.c:87:5
    #7 0x7f9762a6509a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x4c6293 in malloc (/libzip/regress/a.out+0x4c6293)
    #1 0x4ff251 in buffer_new (/libzip/regress/a.out+0x4ff251)
    #2 0x4fe7fc in zip_source_buffer_fragment_create (/libzip/regress/a.out+0x4fe7fc)
    #3 0x4fe75c in zip_source_buffer_create (/libzip/regress/a.out+0x4fe75c)
    #4 0x4f5563 in LLVMFuzzerTestOneInput /libzip/regress/zip_read_fuzzer_.c:16:16
    #5 0x4f58d3 in main /libzip/regress/zip_read_fuzzer_.c:87:5
    #6 0x7f9762a6509a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x4c6293 in malloc (/libzip/regress/a.out+0x4c6293)
    #1 0x4fe81b in zip_source_buffer_fragment_create (/libzip/regress/a.out+0x4fe81b)
    #2 0x4fe75c in zip_source_buffer_create (/libzip/regress/a.out+0x4fe75c)
    #3 0x4f5563 in LLVMFuzzerTestOneInput /libzip/regress/zip_read_fuzzer_.c:16:16
    #4 0x4f58d3 in main /libzip/regress/zip_read_fuzzer_.c:87:5
    #5 0x7f9762a6509a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4c66b2 in realloc (/libzip/regress/a.out+0x4c66b2)
    #1 0x4ff1e9 in buffer_grow_fragments (/libzip/regress/a.out+0x4ff1e9)
    #2 0x4ff352 in buffer_new (/libzip/regress/a.out+0x4ff352)
    #3 0x4fe7fc in zip_source_buffer_fragment_create (/libzip/regress/a.out+0x4fe7fc)
    #4 0x4fe75c in zip_source_buffer_create (/libzip/regress/a.out+0x4fe75c)
    #5 0x4f5563 in LLVMFuzzerTestOneInput /libzip/regress/zip_read_fuzzer_.c:16:16
    #6 0x4f58d3 in main /libzip/regress/zip_read_fuzzer_.c:87:5
    #7 0x7f9762a6509a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4c66b2 in realloc (/libzip/regress/a.out+0x4c66b2)
    #1 0x4ff193 in buffer_grow_fragments (/libzip/regress/a.out+0x4ff193)
    #2 0x4ff352 in buffer_new (/libzip/regress/a.out+0x4ff352)
    #3 0x4fe7fc in zip_source_buffer_fragment_create (/libzip/regress/a.out+0x4fe7fc)
    #4 0x4fe75c in zip_source_buffer_create (/libzip/regress/a.out+0x4fe75c)
    #5 0x4f5563 in LLVMFuzzerTestOneInput /libzip/regress/zip_read_fuzzer_.c:16:16
    #6 0x4f58d3 in main /libzip/regress/zip_read_fuzzer_.c:87:5
    #7 0x7f9762a6509a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: 232 byte(s) leaked in 5 allocation(s)
```

**To Reproduce**
Source for `regress/zip_read_fuzzer_.c`
```
#include "zip.h"

#include <string.h>
#include <stdio.h>
#include <stdlib.h>


int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size)
{
    zip_source_t *src;
    zip_t *za;
    zip_error_t error;

    zip_error_init(&error);
    
    if ((src = zip_source_buffer_create(data, size, 1, &error)) == NULL)
    {
	    zip_error_fini(&error);
	    return 0;
    }
    
    zip_source_keep(src);

    if ((za = zip_open_from_source(src, 0, &error)) == NULL)
    {
        zip_source_free(src);
	    zip_error_fini(&error);
	    return 0;
    }
    
    zip_error_fini(&error);

    char *buf[32768];
    unsigned long n = zip_get_num_entries(za, 0);

    zip_file_t *f;
    unsigned long i;
    for(i=0; i < n; i++)
    {
        f = zip_fopen_index(za, i, 0);
        if(f==NULL) continue;

        while(zip_fread(f, buf, 32768) > 0);
    
        zip_fclose(f);
    }

    zip_close(za);

    return 0;
}

int main(int argc, char **argv)
{
    FILE *zip;
    unsigned char *zipbuf;
    char *filename = argv[1];

    zip = fopen(filename, "rb");

    if(zip==NULL)
    {
        printf("error opening input file %s\n", filename);
        return 1;
    }

    fseek(zip, 0, SEEK_END);
    long siz_zipbuf = ftell(zip);
    rewind(zip);

    zipbuf = (unsigned char*)malloc(siz_zipbuf);
    if(zipbuf==NULL)
    {
        fclose(zip);
        return 0;
    }

    if(fread(zipbuf, siz_zipbuf, 1, zip) != 1)
    {
        printf("fread() failed\n");
        free(zipbuf);
        return 1;
    }

    fclose(zip);

    LLVMFuzzerTestOneInput(zipbuf, siz_zipbuf);

     free(zipbuf);

    return 0;
}
```

```
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=OFF -DENABLE_GNUTLS=OFF -DENABLE_MBEDTLS=OFF -DENABLE_OPENSSL=OFF -DBUILD_TOOLS=OFF ..
make -j5
cd ../regress
clang-7 -g -fsanitize=address zip_read_fuzzer_.c -lz ../build/lib/libzip.a -I../lib -I../build
```

**libzip Version**
master

**Operating System**
Linux

**Test Files**
I tested with random 2-byte files

**Comment by 0-wiz-0** [comment]
Before you pass your code to the fuzzer, can you please make sure it works as intended?
I see some problems immediately:
````
char *buf[32768];
````
should be
````
char buf[32768];
````
and the block
````
 if ((src = zip_source_buffer_create(data, size, 1, &error)) == NULL)
    {
	    zip_error_fini(&error);
	    return 0;
    }
````
should free `data`, but the main function should not, since ownership passes to libzip after
````
zip_source_buffer_create(data, size, 1, &error)
````
because of the `1`.

There is an example in `examples/in-memory.c`.

**Comment by 0-wiz-0** [comment]
Also, test it with a real zip archive, then you can still try 2-byte files.
Thank you!

**Comment by randy408** [comment]
Thanks for the corrections, `data` is not supposed to be freed inside `LLVMFuzzerTestOneInput()` so `zip_source_buffer_create()` is now called with `0`, removing `zip_source_keep(src);` fixed the leaks.
