### ISSUE TITLE
runtime error: null pointer passed as argument 1, which is declared to never be null (zip_extra_field.c:165)

### ISSUE THREAD

**Issue by geeknik** [nih-at/libzip#15]
The attached malformed zip file triggers this undefined behavior/runtime error in `0cf4ff`, compiled with clang 6.0.0-trunk and `-fsanitize=undefined`.

`./ziptool -c test000.zip cat index`

```
zip_extra_field.c:165:65: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:70:33: note: nonnull attribute specified here
    #0 0x51e668 in _zip_ef_merge /root/libzip/lib/zip_extra_field.c:165:58
    #1 0x53f292 in _zip_checkcons /root/libzip/lib/zip_open.c:479:36
    #2 0x53b127 in _zip_find_central_dir /root/libzip/lib/zip_open.c:627:28
    #3 0x53b127 in _zip_open /root/libzip/lib/zip_open.c:194
    #4 0x538617 in zip_open_from_source /root/libzip/lib/zip_open.c:148:11
    #5 0x537f6b in zip_open /root/libzip/lib/zip_open.c:74:15
    #6 0x4fe7bc in read_from_file /root/libzip/src/ziptool.c:709:12
    #7 0x4fe7bc in main /root/libzip/src/ziptool.c:1139
    #8 0x7f0ee8c9cb44 in __libc_start_main /build/glibc-6V9RKT/glibc-2.19/csu/libc-start.c:287
    #9 0x41d1db in _start (/root/libzip/src/ziptool+0x41d1db)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior zip_extra_field.c:165:65 in
Aborted
```

[test000.zip](https://github.com/nih-at/libzip/files/1497751/test000.zip)

**Comment by 0-wiz-0** [comment]
Thanks for the report!
We've just pushed a fix (https://github.com/nih-at/libzip/commit/d038c7bc2c14f7dd3d6d4204b1d79fdba88a3123) for this, please test.

**Comment by geeknik** [comment]
Looks good to me, let's close this one. (=
