### ISSUE TITLE
Incorrect/Inconsistent results produced by `ziptool`

### ISSUE THREAD

**Issue by shao-hua-li** [nih-at/libzip#287]
Hi,

I compiled libzip twice with `clang-13` and `gcc-11` separately. For the provided input zip file, the two versions of `ziptool` would produce different results. To reproduce:

- libzip version: (git HEAD e5902d1cc456154dd94f81df86b29d64f8d8469c)
- Ubuntu 20.04.4 LTS, x86_64
- Compile with `clang-13` and `gcc-11` separately to obtain `ziptool-clang` and `ziptool-gcc`
- Run `ziptool-clang issue-287 cat index > out-clang.txt` and `ziptool-gcc issue-287 cat index > out-gcc.txt`  
[issue-287.tar.gz](https://github.com/nih-at/libzip/files/8173172/issue-287.tar.gz)

- Check the md5sum of the outputs and you'll see they're different.
```
$md5sum out-clang.txt out-gcc.txt
29b2357607a531dbde1332d328f53d9b  out-clang.txt 
48b54e5d7dc11166fd730936ec218a68  out-gcc.txt
```

I also compiled libzip with clang's MemorySanitizer, which reports a use-of-uninitialized-value on the input.
```
Uninitialized bytes in __interceptor_fwrite at offset 0 inside [0x7fffb14ad140, 8192)
==698913==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x4a05f5 in cat /libzip/repo/clang13-mem-Os/src/ziptool.c:188:13
    #1 0x4a4984 in dispatch /libzip/repo/clang13-mem-Os/src/ziptool.c:776:17
    #2 0x4a4984 in main /libzip/repo/clang13-mem-Os/src/ziptool.c:947:15
    #3 0x7f9bce35a0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #4 0x4214cd in _start (/shared/targets/libzip/repo/clang13-mem-Os/build/src/ziptool+0x4214cd)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /libzip/repo/clang13-mem-Os/src/ziptool.c:188:13 in cat
Exiting
```

**Comment by dillof** [comment]
Could you please provide the output files, so we can see what's actually different?

**Comment by 0-wiz-0** [comment]
'issue-287' as included in 'issue-287.tar.gz' is a broken zip archive.
```
# unzip -tq issue-287
bigzero.zip             bad CRC 6aae4d66  (should be ae158154)
At least one error was detected in issue-287.
```

**Comment by shao-hua-li** [comment]
> Could you please provide the output files, so we can see what's actually different?

@dillof I rerun on the input, and here are the new outputs I got:
[out-gcc.txt](https://github.com/nih-at/libzip/files/8176397/out-gcc.txt)
[out-clang.txt](https://github.com/nih-at/libzip/files/8176399/out-clang.txt)
Their md5sums are different from what I reported yesterday. I suspect the reason is that because of the use-of-uninitialized-value, the final output may depend on the process's memory layout during run-time.
To reliably reproduce this issue, I would suggest you try to run the input on different machines/dockers. In this case, it doesn't matter to use which compiler.

**Comment by shao-hua-li** [comment]
> 'issue-287' as included in 'issue-287.tar.gz' is a broken zip archive.
> 
> ```
> # unzip -tq issue-287
> bigzero.zip             bad CRC 6aae4d66  (should be ae158154)
> At least one error was detected in issue-287.
> ```

Yes, you're right. This is a bogus input. However, to ensure the consistency and correctness of libzip, I believe in whatever cases it should consistently produce the same outputs.
